!obj:pylearn2.train.Train {

    dataset: &train !obj:keypoints_dataset.FacialKeypointDataset {
        which_set: 'train',
        start: 0,
        stop: 6500, 
    },

    model: !obj:pylearn2.models.mlp.MLP {
        layers: [
                 !obj:pylearn2.models.mlp.RectifiedLinear {
                     layer_name: 'h0',
                     dim: 500,
                     sparse_init: 15,
                 },
                 !obj:pylearn2.models.mlp.Tanh {
                     layer_name: 'h1',
                     dim: 500,
                     irange: 0.5,
                 },
                 !obj:pylearn2.models.mlp.Linear {
                     layer_name: 'y',
                     dim: 30,
                     sparse_init: 5
                 }
                ],
        nvis: 9216
    },

    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        batch_size: 100,
        learning_rate: 0.001,
        monitoring_dataset:
            {
                'train' : *train ,
                'valid' : !obj:keypoints_dataset.FacialKeypointDataset {
                              which_set: 'train',
                              start: 6500,  
                              stop: 7049,
                          }
            },

        cost: !obj:pylearn2.costs.mlp.missing_target_cost.MissingTargetCost {
        },

        termination_criterion: !obj:pylearn2.termination_criteria.MonitorBased {
            channel_name: "valid_objective",
            prop_decrease: 0.,
            N: 15
        }
    },
    extensions: [
        !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
             channel_name: 'valid_objective',
             save_path: "my_mlp.pkl"
        },
    ]
}
